language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
cache:
  directories:
    - node_modules
notifications:
  email: false
services:
  - rabbitmq
script:
  - npm run test:lint
  - npm run test:coverage
  - npm run test:integration
  - npm run report:coverage
