version: '2.2'
services:
    rabbitmq:
        image: rabbitmq:3.6.14-management
        ports:
          - "8080:8080"
          - "15672:15672"
          - "5672:5672"
        expose:
          - "8080"
          - "15672"
          - "5672"
